name: Keep Render App Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:         # lets you run it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping endpoint
        run: curl -s https://movie-reco-p0tq.onrender.com/api/embed
